#-------------------------------
# General Site Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://summitadvisors.ad" # the base hostname & protocol for your site, e.g. http://example.com

languages:
  - en
  - es
  - cat

#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page/:num"

# Publish future-dated posts
future: true

#-------------------------------
# Collections
collections:
  pages:
    output: true
    permalink: /:name
  es_posts:
    output: true
    permalink: /es/blog/:name
  en_posts:
    output: true
    permalink: /en/blog/:name
  cat_posts:
    output: true
    permalink: /cat/blog/:name
  projects:
    output: true
    permalink: /project/:slug

# Pages Path
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

sass:
  sass_dir: _sass
  style: compressed
