#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Servicios'
      url: '/projects/'
    - url: '/about/'
      title: 'Nosotros'
    - url: '/andorra/'
      title: 'Andorra'
    - url: '/calculadora/'
      title: 'Calculadora'
    - title: 'Blog'
      url: '/blog/'
    - url: '/contact/'
      title: 'Contacto'
    - title: 'Español'
      submenu:
      - url: '/elements/'
        title: 'English'


#-------------------------------
# Author Settings
author:
  author__name: Summit Advisors
  author__bio: Si estás plantéandote moverte a Andorra y disfrutar de sus ventajas tanto fiscales cómo de estilo de vida, hablemos más en detalle.
  author__avatar: '/images/summit.png'

social:
- {icon: "ion-logo-twitter", link: "https://twitter.com"}
- {icon: "ion-logo-facebook", link: "https://facebook.com"}
- {icon: "ion-logo-instagram", link: "https://instagram.com"}
- {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
- {icon: "ion-logo-github", link: "https://github.com"}

# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Newsletter
mailchimp: enable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
mailchimp__input__text: Tu dirección de email...
mailchimp__button__text: Te contactamos


#-------------------------------
# Projects Settings
projects__settings:
  projects__title: Servicios
  projects__description: Ofrecemos servicios personalizados a tu caso específico de manera totalmente transparente y directa.

#-------------------------------
# Blog Section
blog__settings:
  blog__title: Últimas entradas
  blog__description:


#-------------------------------
# Gallery Footer Settings
gallery:
  gallery__images:
    - alt: 'Rest'
      url: '/images/andorra/andorra-la-vella.jpg'
      # url: '/images/gallery-1.jpg'
    - alt: 'Lifestyle'
      # url: '/images/gallery-2.jpg'
      url: 'https://media.istockphoto.com/photos/embankment-of-valira-d-orient-river-in-la-cortinada-andorra-picture-id492005666?k=20&m=492005666&s=612x612&w=0&h=i-4WRA_UUyOP8utOJ5zjoCO-I8qtqDbWLCugDkxDsTE='
    - alt: 'Hobby'
      # url: '/images/gallery-3.jpg'
      url: 'https://media.istockphoto.com/photos/main-highway-in-andorra-picture-id849558280?k=20&m=849558280&s=612x612&w=0&h=AUTo9r7eL0_XAGUpmEGioqcmYvifFw3CvmKeaHpuVCc='
    - alt: 'Notes'
      # url: '/images/gallery-4.jpg'
      url: 'https://media.istockphoto.com/photos/view-of-the-village-in-the-pyrenees-andorra-from-the-ski-slopes-in-picture-id1160844746?k=20&m=1160844746&s=612x612&w=0&h=2LIxl_jpBZg4BebcJB38i8XjY_0t-c0s_otAfX3e_5c='


#-------------------------------
# Footer Navigation Settings
footer_menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Servicios'
      url: '/projects/'
    - title: 'Blog'
      url: '/blog/'
    - url: '/about/'
      title: 'Nosotros'
    - url: '/andorra/'
      title: 'Andorra'
    - url: '/calculadora/'
      title: 'Calculadora'
    - url: '/contact/'
      title: 'Contacto'
    - url: '/elements/'
      title: 'Elements'


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvodstudio-demo # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id