#-------------------------------
# Author Settings
author:
  author__name: Summit Advisors
  author__bio: Si estás plantéandote moverte a Andorra y disfrutar de sus ventajas tanto fiscales cómo de estilo de vida, hablemos más en detalle.
  author__avatar: '/images/summit.png'

# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Newsletter
mailchimp: enable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
mailchimp__input__text: Tu dirección de email...
mailchimp__button__text: Te contactamos


#-------------------------------
# Projects Settings
projects__settings:
  projects__title: Servicios
  projects__description: Ofrecemos servicios personalizados a tu caso específico de manera totalmente transparente y directa.

#-------------------------------
# Blog Section
blog__settings:
  blog__title: Últimas entradas
  blog__description:

#-------------------------------
# Footer Navigation Settings
footer_menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Servicios'
      url: '/projects/'
    - title: 'Blog'
      url: '/blog/'
    - url: '/about/'
      title: 'Nosotros'
    - url: '/andorra/'
      title: 'Andorra'
    - url: '/calculadora/'
      title: 'Calculadora'
    - url: '/contact/'
      title: 'Contacto'
    - url: '/elements/'
      title: 'Elements'


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvodstudio-demo # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id