# config.yml

display_url: summit-advisors.netlify.app
locale: 'es'
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'general'
    label: 'General'
    editor:
      preview: false
    files:
    - label: "Homepage"
      name: "home"
      file: "_data/homepage.yml"
      fields: 
        - { label: Título principal, name: hero__title, widget: string, hint: 'Título de cabecera en la homepage' }
        - { label: Subtítulo, name: hero__description, widget: string, hint: 'Descripción bajo el título de cabecera' }
        - { label: Imagén Principal, name: hero__image, widget: image, choose_url: true, hint: 'Imagen principal' }
        - { label: Título sección de Testimonios, name: testimonial__title, widget: string, hint: 'En la homepage, en la sección de Testimonios' }
        - { label: Descripción sección de Testimonios, name: testimonial__description, widget: string, hint: 'En la homepage, en la sección de Testimonios' }
    - label: "Testimonials"
      name: "testimonial__items"
      widget: "list"
      file: "_data/testimonials.yml"
      fields: 
        - { label: Nombre, name: name, widget: string, hint: 'Nombre de la persona que da el testimonio' }
        - { label: Oficio, name: designation, widget: string, hint: 'Ocupación' }
        - { label: Hero Image, name: image, widget: image, choose_url: true, hint: 'Imagen de la persona' }
        - { label: Link, name: link, widget: string, hint: 'Enlace externo que representa a la persona', required: false }
        - { label: Content, name: content, widget: string, hint: 'Testimonio, una sola frase.' }
  - name: 'pages'
    label: 'Páginas'
    folder: '_pages/'
    create: false
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Permalink', name: 'permalink', widget: 'hidden' }
      - { label: 'Descripción', name: 'description', widget: 'string' }
      - { label: 'Imagen de cabecera', name: 'image', widget: 'image' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Descripción', name: 'description', widget: 'string' }
      - { label: 'Fecha de publicación', name: 'date', widget: 'datetime' }
      - { label: 'Imagen de cabecera', name: 'image', widget: 'image' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'services'
    label: 'Servicios'
    folder: '_projects/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Subtitlo', name: 'subtitle', hint:'Texto bajo el título', widget: 'string' }
      - { label: 'Descripción', name: 'description', widget: 'string' }
      - { label: 'Fecha de publicación', name: 'date', widget: 'datetime' }
      - { label: 'Imagen de cabecera', name: 'image', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }