# config.yml

display_url: https://summit-advisors.netlify.app
locale: 'es'
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# when using the default proxy server port
local_backend: true
media_folder: 'assets/uploads'
collections:
  - name: 'general'
    label: 'General'
    editor:
      preview: false
    files:
    - label: "Homepage"
      name: "home"
      file: "_data/hero.yml"
      fields: 
        - { label: 'Título principal (Español)', name: 'hero__title_es', widget: 'string', hint: 'Título de cabecera en la homepage' }
        - { label: 'Título principal (Inglés)', name: 'hero__title_en', widget: 'string', hint: 'Título de cabecera en la homepage' }
        - { label: 'Título principal (Catalàn)', name: 'hero__title_cat', widget: 'string', hint: 'Título de cabecera en la homepage' }
        - { label: 'Subtítulo (Español)', name: 'hero__description_es', widget: 'string', hint: 'Descripción bajo el título de cabecera' }
        - { label: 'Subtítulo (Inglés)', name: 'hero__description_en', widget: 'string', hint: 'Descripción bajo el título de cabecera' }
        - { label: 'Subtítulo (Catalàn)', name: 'hero__description_cat', widget: 'string', hint: 'Descripción bajo el título de cabecera' }
        - { label: Imagén Principal, name: hero__image, widget: image, choose_url: true, hint: 'Imagen principal' }
    - label: "Testimonios de Clientes"
      name: "testimonials"
      file: "_data/testimonials.yml"
      fields: 
        - label: 'Título sección de Testimonios (Español)'
          name: 'testimonial__title_es'
          widget: 'string'
          hint: 'En la homepage, en la sección de Testimonios'
        - label: 'Título sección de Testimonios (Inglés)'
          name: 'testimonial__title_en'
          widget: 'string'
          hint: 'On the homepage, in the Testimonials section'
        - label: 'Título sección de Testimonios (Catalàn)'
          name: 'testimonial__title_cat'
          widget: 'string'
          hint: 'A la homepage, a la secció de Testimonis'
        - label: "Descripción sección de Testimonios (Español)"
          name: testimonial__description_es
          required: false
          widget: string
          hint: 'En la homepage, en la sección de Testimonios'
        - label: "Descripción sección de Testimonios (Inglés)"
          name: testimonial__description_en
          required: false
          widget: string
          hint: 'En la homepage, en la sección de Testimonios'
        - label: "Descripción sección de Testimonios (Catalan)"
          name: testimonial__description_cat
          required: false
          widget: string
          hint: 'En la homepage, en la sección de Testimonios'
        - label: "Testimonios de Clientes"
          name: "testimonial__items"
          widget: "list"
          fields:
          - { label: Nombre, name: name, widget: string, hint: 'Nombre de la persona que da el testimonio' }
          - { label: Oficio (Español), name: designation_es, widget: string, hint: 'Ocupación' }
          - { label: Oficio (Inglés), name: designation_en, widget: string, hint: 'Ocupación' }
          - { label: Oficio (Catalán), name: designation_cat, widget: string, hint: 'Ocupación' }
          - { label: Hero Image, name: image, widget: image, choose_url: true, hint: 'Imagen de la persona' }
          - { label: Link, name: link, widget: string, hint: 'Enlace externo que representa a la persona', required: false }
          - { label: Testimonio (Español), name: content_es, widget: string, hint: 'Testimonio, una sola frase.' }
          - { label: Testimonio (Inglés), name: content_en, widget: string, hint: 'Testimonio, una sola frase.' }
          - { label: Testimonio (Catalán), name: content_cat, widget: string, hint: 'Testimonio, una sola frase.' }
    - label: "Contacto"
      name: "contact"
      file: "_data/contact.yml"
      fields: 
        - { label: "Descripción (Español)", name: description_es, widget: text, hint: 'Descripción del formulario de contacto en español' }
        - { label: "Descripción (Inglés)", name: description_en, widget: text, hint: 'Descripción del formulario de contacto en inglés' }
        - { label: "Descripción (Catalàn)", name: description_cat, widget: text, hint: 'Descripción del formulario de contacto en catalán' }
  - name: 'pages'
    label: 'Páginas (Español)'
    folder: '_pages/es/'
    filter: {field: "CMSeditable", value: true}
    create: false
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Permalink', name: 'permalink', widget: 'hidden' }
      - { label: 'Descripción', name: 'description', widget: 'string', required: false }
      - { label: 'Imagen de cabecera', name: 'image', widget: 'image', required: false }
      - { label: 'Idioma', name: 'language', widget: 'hidden', default: 'es' }
      - { label: 'Ref', name: 'ref', required: false, widget: 'string', hint: 'Usar el mismo ref permite cambiar fácilmente entre idiomas sin pasar por el homepage. Por ejemplo cambiar entre /es/andorra y /en/andorra.' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'es_blog'
    label: 'Blog (Español)'
    folder: '_es_posts/'
    create: true
    editor:
      preview: false
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Descripción', name: 'description', widget: 'string' }
      - { label: 'Fecha de publicación', name: 'date', widget: 'datetime' }
      - { label: 'Imagen de cabecera', name: 'image', widget: 'image' }
      - label: 'Tags'
        name: 'tags'
        required: false
        widget: 'relation'
        collection: 'tags'
        searchFields: ['tags.*.es']  # Search Spanish names in all tags
        valueField: 'tags.*.code'   # Reference the code of the tag
        displayFields: ['tags.*.es'] # Display the Spanish name of the tag
        multiple: true
      - { label: 'Idioma', name: 'language', widget: 'hidden', default: 'es' }
      - { label: 'Ref', name: 'ref', required: false, widget: 'string', hint: 'Usar el mismo ref permitirá cambiar fácilmente entre idiomas sin pasar por el homepage.' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'en_blog'
    label: 'Blog (Inglés)'
    folder: '_en_posts/'
    create: true
    editor:
      preview: false
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Descripción', name: 'description', widget: 'string' }
      - { label: 'Fecha de publicación', name: 'date', widget: 'datetime' }
      - { label: 'Imagen de cabecera', name: 'image', widget: 'image' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Idioma', name: 'language', widget: 'hidden', default: 'en' }
      - { label: 'Ref', name: 'ref', required: false, widget: 'string', hint: 'Usar el mismo ref permitirá cambiar fácilmente entre idiomas sin pasar por el homepage.' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'cat_blog'
    label: 'Blog (Catalán)'
    folder: '_cat_posts/'
    create: true
    editor:
      preview: false
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Descripción', name: 'description', widget: 'string' }
      - { label: 'Fecha de publicación', name: 'date', widget: 'datetime' }
      - { label: 'Imagen de cabecera', name: 'image', widget: 'image' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Idioma', name: 'language', widget: 'hidden', default: 'cat' }
      - { label: 'Ref', name: 'ref', required: false, widget: 'string', hint: 'Usar el mismo ref permite cambiar fácilmente entre idiomas sin pasar por el homepage. Por ejemplo cambiar entre /es/andorra y /en/andorra.' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'services'
    label: 'Servicios (Español)'
    folder: '_projects/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Subtitlo', name: 'subtitle', hint:'Texto bajo el título', widget: 'string' }
      - { label: 'Descripción', name: 'description', widget: 'string' }
      - { label: 'Fecha de publicación', name: 'date', widget: 'datetime' }
      - { label: 'Imagen de cabecera', name: 'image', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'Ajustes'
    label: 'Ajustes'
    editor:
      preview: false
    files:
    - label: "Calculadora (Parámetros)"
      name: "calculator"
      file: "_data/calculator.yml"
      fields: 
        - { label: tramo Mínimo, name: tramoMin, widget: number, hint: 'En Euros, por ejemplo 24000' }
        - { label: tramo Máximo, name: tramoMax, widget: number, hint: 'En Euros, por ejemplo 40000' }
        - { label: tributacion Tramo Minínimo, name: tributacionMin, widget: number, hint: 'En porcentaje, por ejemplo 5' }
        - { label: tributacion Tramo Máximo, name: tributacionMax, widget: number, hint: 'En porcentaje, por ejemplo 10' }
        - { label: impuesto de Sociedades, name: impuestoSociedades, widget: number, hint: 'En porcentaje, por ejemplo 10' }
        - { label: Seguridad Social como Autónomo, name: seguridadSocial, widget: number, hint: 'En Euros, por ejemplo 502.63', value_type: float }
        - { label: Texto Botón, name: placeholder, widget: string, hint: '' }
        - { label: Botón, name: buttonCTA, widget: string, hint: '' }
    - label: "Fotos del Footer"
      name: "footer"
      file: "_data/footer.yml"
      fields: 
        - label: "Galeria del Footer"
          name: "gallery"
          widget: "list"
          fields:
          - { label: Titulo, name: alt, widget: string, hint: 'Nombre de la imagen por motivos de SEO de Google.' }
          - { label: Imagen, name: url, widget: image, choose_url: true, hint: 'Imagen que aparece en el footer en todas las páginas.' }
    - label: "Ajustes Globales"
      name: "global"
      file: "_data/global.yml"
      fields: 
        - { label: Título principal, name: title, widget: string, hint: 'Título de la página para el SEO' }
        - { label: Descripción (Español), name: description_es, widget: string, hint: 'Descripción de la página para el SEO en español' }
        - { label: Descripción (Inglés), name: description_en, widget: string, hint: 'Descripción de la página para el SEO en inglés' }
        - { label: Descripción (Catalán), name: description_cat, widget: string, hint: 'Descripción de la página para el SEO en catalán' }
        - { label: Logo Fondo Oscuro, name: logo_dark, widget: image, required: false, hint: 'Logo que aparecería en todas las páginas en la esquina superior izquierda' }
        - { label: Logo Fondo Blanco, name: logo_light, widget: image, required: false, hint: 'Logo que aparecería en todas las páginas en la esquina superior izquierda' }
        - { label: Color de la página, name: color_scheme, widget: select, options: ["auto", "light", "dark"], hint: 'Auto permite al usuario elegir si quiere ver la página clara u oscura haciendo click en el icono de arriba a la derecha. Las otras opciones fuerzan la decisión.' }
        - { label: Color de Marca para theme dark (HEX), name: brand_color_dark, widget: string, required: false, hint: 'Cuando el usuario visualize el theme oscuro (dark) el color de contraste para botones y selecciones será este. Por defecto es: #ad72df' }
        - { label: Color de Marca para theme light (HEX), name: brand_color_light, widget: string, required: false, hint: 'Cuando el usuario visualize el theme claro (light) el color de contraste para botones y selecciones será este. Por defecto es: #fec824' }
    - label: "Redes Sociales"
      name: "social"
      file: "_data/social.yml"
      fields:
        - label: "Redes Sociales"
          name: "social"
          widget: "list"
          collapse: false
          fields:
            - { label: Icono, name: icon, widget: string, hint: 'Otros iconos se pueden encontrar en https://ionicons.com/v4/ , usar el mismo formato (ion- delante del nombre del icono).' }
            - { label: Link, name: link, widget: string, hint: "Enlace a la red social elegida." }
  - name: "tags"
    label: "Tags"
    files:
      - name: "tags_file"
        label: "Lista de Tags (no borrar tags vinculados a blog posts)"
        file: "_data/tags.yml"
        collection: "tags"
        fields:
          - label: "Tags List"
            name: "tags"
            widget: "list"
            fields:
              - { label: "Tag Code", name: "code", widget: "string" }
              - { label: "Tag Name (Spanish)", name: "es", widget: "string" }
              - { label: "Tag Name (Inglés)", name: "en", widget: "string" }
              - { label: "Tag Name (Catalan)", name: "cat", widget: "string" }