# config.yml

display_url: summit-advisors.netlify.app
locale: 'es'
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'pages'
    label: 'Páginas'
    folder: '_pages/'
    create: false
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Permalink', name: 'permalink', widget: 'hidden' }
      - { label: 'Descripción', name: 'description', widget: 'string' }
      - { label: 'Imagen de cabecera', name: 'image', widget: 'image' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Descripción', name: 'description', widget: 'string' }
      - { label: 'Fecha de publicación', name: 'date', widget: 'datetime' }
      - { label: 'Imagen de cabecera', name: 'image', widget: 'image' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'services'
    label: 'Servicios'
    folder: '_projects/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Subtitlo', name: 'subtitle', hint:'Texto bajo el título', widget: 'string' }
      - { label: 'Descripción', name: 'description', widget: 'string' }
      - { label: 'Fecha de publicación', name: 'date', widget: 'datetime' }
      - { label: 'Imagen de cabecera', name: 'image', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }