# config.yml

display_url: https://summit-advisors.netlify.app
locale: 'es'
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# when using the default proxy server port
local_backend: true
media_folder: 'assets/uploads'
collections:
  - name: 'general'
    label: 'General'
    editor:
      preview: false
    files:
    - label: "Homepage"
      name: "home"
      file: "_data/homepage.yml"
      fields: 
        - { label: Título principal, name: hero__title, widget: string, hint: 'Título de cabecera en la homepage' }
        - { label: Subtítulo, name: hero__description, widget: string, hint: 'Descripción bajo el título de cabecera' }
        - { label: Imagén Principal, name: hero__image, widget: image, choose_url: true, hint: 'Imagen principal' }
    - label: "Calculadora"
      name: "calculator"
      file: "_data/calculator.yml"
      fields: 
        - { label: tramo Mínimo, name: tramoMin, widget: number, hint: 'En Euros, por ejemplo 24000' }
        - { label: tramo Máximo, name: tramoMax, widget: number, hint: 'En Euros, por ejemplo 40000' }
        - { label: tributacion Tramo Minínimo, name: tributacionMin, widget: number, hint: 'En porcentaje, por ejemplo 5' }
        - { label: tributacion Tramo Máximo, name: tributacionMax, widget: number, hint: 'En porcentaje, por ejemplo 10' }
        - { label: impuesto de Sociedades, name: impuestoSociedades, widget: number, hint: 'En porcentaje, por ejemplo 10' }
        - { label: Texto Botón, name: placeholder, widget: string, hint: '' }
        - { label: Botón, name: buttonCTA, widget: string, hint: '' }
    - label: "Testimonios de Clientes"
      name: "testimonials"
      file: "_data/testimonials.yml"
      fields: 
        - label: "Título sección de Testimonios"
          name: testimonial__title
          widget: string
          hint: 'En la homepage, en la sección de Testimonios'
        - label: "Descripción sección de Testimonios"
          name: testimonial__description
          required: false
          widget: string
          hint: 'En la homepage, en la sección de Testimonios'
        - label: "Testimonios de Clientes"
          name: "testimonial__items"
          widget: "list"
          fields:
          - { label: Nombre, name: name, widget: string, hint: 'Nombre de la persona que da el testimonio' }
          - { label: Oficio, name: designation, widget: string, hint: 'Ocupación' }
          - { label: Hero Image, name: image, widget: image, choose_url: true, hint: 'Imagen de la persona' }
          - { label: Link, name: link, widget: string, hint: 'Enlace externo que representa a la persona', required: false }
          - { label: Content, name: content, widget: string, hint: 'Testimonio, una sola frase.' }
    - label: "Footer"
      name: "footer"
      file: "_data/footer.yml"
      fields: 
        - label: "Testimonios de Clientes"
          name: "gallery"
          widget: "list"
          fields:
          - { label: Titulo, name: alt, widget: string, hint: 'Nombre de la imagen por motivos de SEO de Google.' }
          - { label: Imagen, name: url, widget: image, choose_url: true, hint: 'Imagen que aparece en el footer en todas las páginas.' }
    - label: "Contacto"
      name: "contact"
      file: "_data/contact.yml"
      fields: 
        - { label: Descripción, name: description, widget: string, hint: 'Descripción del formulario de contacto' }
    - label: "Ajustes"
      name: "global"
      file: "_data/global.yml"
      fields: 
        - { label: Título principal, name: title, widget: string, hint: 'Título de la página para el SEO' }
        - { label: Descripción, name: description, widget: string, hint: 'Descripción de la página para el SEO' }
        - { label: Logo Fondo Oscuro, name: logo_dark, widget: image, required: false, hint: 'Logo que aparecería en todas las páginas en la esquina superior izquierda' }
        - { label: Logo Fondo Blanco, name: logo_light, widget: image, required: false, hint: 'Logo que aparecería en todas las páginas en la esquina superior izquierda' }
        - { label: Color de la página, name: color_scheme, widget: select, options: ["auto", "light", "dark"], hint: 'Auto permite al usuario elegir si quiere ver la página clara u oscura haciendo click en el icono de arriba a la derecha. Las otras opciones fuerzan la decisión.' }
        - { label: Color de Marca para theme dark (HEX), name: brand_color_dark, widget: string, required: false, hint: 'Cuando el usuario visualize el theme oscuro (dark) el color de contraste para botones y selecciones será este. Por defecto es: #ad72df' }
        - { label: Color de Marca para theme light (HEX), name: brand_color_light, widget: string, required: false, hint: 'Cuando el usuario visualize el theme claro (light) el color de contraste para botones y selecciones será este. Por defecto es: #fec824' }
    - label: "Social Links"
      name: "social"
      file: "_data/social.yml"
      fields:
        - label: "Redes Sociales"
          name: "social"
          widget: "list"
          collapse: false
          fields:
            - { label: Icono, name: icon, widget: string }
            - { label: Link, name: link, widget: string }
  - name: 'pages'
    label: 'Páginas'
    folder: '_pages/'
    create: false
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Permalink', name: 'permalink', widget: 'hidden' }
      - { label: 'Descripción', name: 'description', widget: 'string', required: false }
      - { label: 'Imagen de cabecera', name: 'image', widget: 'image' }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Descripción', name: 'description', widget: 'string' }
      - { label: 'Fecha de publicación', name: 'date', widget: 'datetime' }
      - { label: 'Imagen de cabecera', name: 'image', widget: 'image' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'services'
    label: 'Servicios'
    folder: '_projects/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Subtitlo', name: 'subtitle', hint:'Texto bajo el título', widget: 'string' }
      - { label: 'Descripción', name: 'description', widget: 'string' }
      - { label: 'Fecha de publicación', name: 'date', widget: 'datetime' }
      - { label: 'Imagen de cabecera', name: 'image', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }